// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: product.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductRPCClient is the client API for ProductRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductRPCClient interface {
	GetProductsByMenuTypeID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ProductSlice, error)
	GetProductByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Product, error)
	SearchProducts(ctx context.Context, in *Word, opts ...grpc.CallOption) (*ProductSlice, error)
	GetRestaurantIDByProduct(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ID, error)
}

type productRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewProductRPCClient(cc grpc.ClientConnInterface) ProductRPCClient {
	return &productRPCClient{cc}
}

func (c *productRPCClient) GetProductsByMenuTypeID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ProductSlice, error) {
	out := new(ProductSlice)
	err := c.cc.Invoke(ctx, "/product.ProductRPC/GetProductsByMenuTypeID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRPCClient) GetProductByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductRPC/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRPCClient) SearchProducts(ctx context.Context, in *Word, opts ...grpc.CallOption) (*ProductSlice, error) {
	out := new(ProductSlice)
	err := c.cc.Invoke(ctx, "/product.ProductRPC/SearchProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRPCClient) GetRestaurantIDByProduct(ctx context.Context, in *ID, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/product.ProductRPC/GetRestaurantIDByProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductRPCServer is the server API for ProductRPC service.
// All implementations should embed UnimplementedProductRPCServer
// for forward compatibility
type ProductRPCServer interface {
	GetProductsByMenuTypeID(context.Context, *ID) (*ProductSlice, error)
	GetProductByID(context.Context, *ID) (*Product, error)
	SearchProducts(context.Context, *Word) (*ProductSlice, error)
	GetRestaurantIDByProduct(context.Context, *ID) (*ID, error)
}

// UnimplementedProductRPCServer should be embedded to have forward compatible implementations.
type UnimplementedProductRPCServer struct {
}

func (UnimplementedProductRPCServer) GetProductsByMenuTypeID(context.Context, *ID) (*ProductSlice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsByMenuTypeID not implemented")
}
func (UnimplementedProductRPCServer) GetProductByID(context.Context, *ID) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedProductRPCServer) SearchProducts(context.Context, *Word) (*ProductSlice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedProductRPCServer) GetRestaurantIDByProduct(context.Context, *ID) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantIDByProduct not implemented")
}

// UnsafeProductRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductRPCServer will
// result in compilation errors.
type UnsafeProductRPCServer interface {
	mustEmbedUnimplementedProductRPCServer()
}

func RegisterProductRPCServer(s grpc.ServiceRegistrar, srv ProductRPCServer) {
	s.RegisterService(&ProductRPC_ServiceDesc, srv)
}

func _ProductRPC_GetProductsByMenuTypeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).GetProductsByMenuTypeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductRPC/GetProductsByMenuTypeID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).GetProductsByMenuTypeID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRPC_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductRPC/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).GetProductByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRPC_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Word)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductRPC/SearchProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).SearchProducts(ctx, req.(*Word))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRPC_GetRestaurantIDByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRPCServer).GetRestaurantIDByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductRPC/GetRestaurantIDByProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRPCServer).GetRestaurantIDByProduct(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductRPC_ServiceDesc is the grpc.ServiceDesc for ProductRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductRPC",
	HandlerType: (*ProductRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductsByMenuTypeID",
			Handler:    _ProductRPC_GetProductsByMenuTypeID_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductRPC_GetProductByID_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _ProductRPC_SearchProducts_Handler,
		},
		{
			MethodName: "GetRestaurantIDByProduct",
			Handler:    _ProductRPC_GetRestaurantIDByProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
