definitions:
  store.Restaurant:
    properties:
      Category:
        type: string
      CommentsCount:
        type: integer
      DeliveryPrice:
        type: integer
      DeliveryTime:
        type: integer
      ID:
        type: integer
      Icon:
        type: string
      Name:
        type: string
      Rating:
        type: number
    type: object
    example:
      Category: "Italian"
      CommentsCount: 10
      DeliveryPrice: 5
      DeliveryTime: 30
      ID: 1
      Icon: "italian-icon.png"
      Name: "Italiano Ristorante"
      Rating: 4.5
  store.User:
    properties:
      Email:
        type: string
      ID:
        type: integer
      Password:
        type: string
      Username:
        type: string
    type: object
    example:
      Email: "user@example.com"
      ID: 1
      Password: "mypassword"
      Username: "myusername"
host: http://84.23.53.216:8001/
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Prinesi-Poday API
  version: "1.0"
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: checking auth
      parameters:
      - description: cookie
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success authenticate return id
          schema:
            type: integer
        "401":
          description: unauthorized
          schema: {}
      summary: checking auth
      tags:
      - users
  /login:
    post:
      consumes:
      - application/json
      description: Log in user
      parameters:
      - description: login
        in: body
        name: login
        required: true
        schema:
          type: string
        example: "user123"
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
        example: "mypassword"
      produces:
      - application/json
      responses:
        "200":
          description: success log in User return cookie
          schema:
            type: string
        "400":
          description: bad request
          schema: {}
        "404":
          description: not found
          schema: {}
        "500":
          description: internal server error
          schema: {}
      summary: Log in user
      tags:
      - users
  /logout:
    get:
      consumes:
      - application/json
      description: Log out user
      parameters:
      - description: cookie
        in: header
        name: cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: void" "success log out
        "400":
          description: bad request
          schema: {}
        "401":
          description: unauthorized
          schema: {}
      summary: Log out user
      tags:
      - users
  /restaurants:
    get:
      consumes:
      - '*/*'
      description: giving array of restaurants
      produces:
      - application/json
      responses:
        "200":
          description: success returning array of restaurants
          schema:
            items:
              $ref: '#/definitions/store.Restaurant'
            type: array
        "500":
          description: internal server error
          schema: {}
      summary: giving restaurats
      tags:
      - Restaurants
  /users:
    post:
      consumes:
      - application/json
      description: Signing up a user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/store.User'
      produces:
      - application/json
      responses:
        "200":
          description: success create User return id
          schema:
            type: integer
        "400":
          description: bad request
          schema: {}
        "500":
          description: internal server error
          schema: {}
      summary: Signing up a user
      tags:
      - users
swagger: "2.0"
