// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DBReqCreateComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DBReqCreateComment ) UnmarshalJSON([]byte) error { return nil }
func ( DBReqCreateComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DBReqCreateComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DBReqCreateComment *DBReqCreateComment

func ( DBRespCreateComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DBRespCreateComment ) UnmarshalJSON([]byte) error { return nil }
func ( DBRespCreateComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DBRespCreateComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DBRespCreateComment *DBRespCreateComment

func ( DBRespGetComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DBRespGetComment ) UnmarshalJSON([]byte) error { return nil }
func ( DBRespGetComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DBRespGetComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DBRespGetComment *DBRespGetComment

func ( ReqCreateComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReqCreateComment ) UnmarshalJSON([]byte) error { return nil }
func ( ReqCreateComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReqCreateComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReqCreateComment *ReqCreateComment

func ( RespComments ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RespComments ) UnmarshalJSON([]byte) error { return nil }
func ( RespComments ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RespComments ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RespComments *RespComments

func ( RespCreateComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RespCreateComment ) UnmarshalJSON([]byte) error { return nil }
func ( RespCreateComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RespCreateComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RespCreateComment *RespCreateComment

func ( RespGetComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RespGetComment ) UnmarshalJSON([]byte) error { return nil }
func ( RespGetComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RespGetComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RespGetComment *RespGetComment
